apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-app-pod
        app: demo-voting-app 
    spec:
      containers:
        - name: postgres-app
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRE_USER
              value: "postgres"
            - name: POSTGRE_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"