apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-app-pod
    name: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379